#!/bin/bash
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"
export XDG_CACHE_HOME="$HOME/.cache"
export QT_IM_MODULE=fcitx5
export XMODIFIERS=@im=fcitx5
export CARGO_HOME="$XDG_DATA_HOME"/cargo
export BUN_INSTALL="$XDG_DATA_HOME"/bun
export DENO_INSTALL="$XDG_DATA_HOME"/deno
export WINEPREFIX="$XDG_DATA_HOME"/wine
export WGETRC="$XDG_CONFIG_HOME/wgetrc"
export W3M_DIR="$XDG_DATA_HOME"/w3m
export CUDA_CACHE_PATH="$XDG_CACHE_HOME"/nv
export LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH
export DOTNET_CLI_HOME="$XDG_DATA_HOME"/dotnet
export RUSTUP_HOME="$XDG_DATA_HOME"/rustup
export BUNDLE_USER_CONFIG="$XDG_CONFIG_HOME"/bundle
export BUNDLE_USER_CACHE="$XDG_CACHE_HOME"/bundle
export INPUTRC="$XDG_CONFIG_HOME"/readline/inputrc
export _JAVA_OPTIONS=-Djava.util.prefs.userRoot="$XDG_CONFIG_HOME"/java
export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME"/npm/npmrc
export IPYTHONDIR="$XDG_CONFIG_HOME/ipython"
export BUNDLE_USER_PLUGIN="$XDG_DATA_HOME"/bundle
export ANSIBLE_HOME="$XDG_DATA_HOME"/ansible
# export CLICOLOR_FORCE=1
export HOMEBREW_PREFIX=/home/linuxbrew/.linuxbrew
export HOMEBREW_NO_ANALYTICS=1
export MANROFFOPT="-c"
export MANPAGER="sh -c 'col -bx | bat -l man -p'"
export MANPATH="${MANPATH-$(manpath)}:/home/theo/.local/share/npm/share/man:/home/theo/programs/texlive/2024/texmf-dist/doc/man"
export HISTORY_IGNORE="ls *:ll *:cd *:pwd:exit:history"
export HISTSIZE=50000
export SAVEHIST=10000
export HISTTIMEFORMAT="%Y/%m/%d %H:%M:%S "
export HISTCONTROL=ignoreboth
export HISTDUP=erase
export SBCL_HOME="/home/theo/programs/sbcl/lib/sbcl"
export GOBIN="/home/theo/.local/share/go/bin"
export GOPATH="/home/theo/.local/share/go"
export FZF_CTRL_T_COMMAND="fd --hidden --strip-cwd-prefix --exclude .git --exclude .github"
export FZF_ALT_C_COMMAND="fd --type d --hidden --strip-cwd-prefix --exclude .git --exclude .github"
export FZF_CTRL_T_OPTS="--select-1 --exit-0"
export FZF_CTRL_R_OPTS="--preview 'echo {}' --preview-window down:3:hidden:wrap --bind '?:toggle-preview'"
export FZF_ALT_C_OPTS="--preview 'tree -C {} | head -200' --select-1 --exit-0"
export FZF_DEFAULT_OPTS="$FZF_DEFAULT_OPTS --ansi"

if [[ "$(uname -a)" == *WSL* ]]; then
  machine="wsl"
elif [[ -f /etc/fedora-release ]]; then
  machine="fedora"
else
  machine="unknown"
fi

case $machine in
  "wsl")
    export UNISON="$XDG_CONFIG_HOME/unison"
    export PATH=:$PATH
    export EDITOR="$HOMEBREW_PREFIX/bin/nvim"
    export VISUAL="$HOMEBREW_PREFIX/bin/nvim"
    export DISPLAY=localhost:0
    export WAYLAND_DISPLAY=$DISPLAY
    export LIBGL_ALWAYS_INDIRECT=1
    export XDG_SESSION_TYPE=x11
    if [[ -n $SSH_TTY ]]; then
      export HTTP_PROXY="http://127.0.0.0:7897"
      export HTTPS_PROXY="http://127.0.0.1:7897"
    fi
    ;;
  "fedora")
    export HTTPS_PROXY=http://127.0.0.1:7897
    export HTTP_PROXY=http://127.0.0.1:7897
    export ALL_PROXY=socks5://127.0.0.1:7897
    export NO_PROXY="127.0.0.1,::1,localhost"
    export EDITOR="nvim"
    export VISUAL="nvim"
    ;;
esac

if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

if [[ -f "$XDG_CONFIG_HOME"/bash/bashrc ]]; then
  source "$XDG_CONFIG_HOME"/bash/bashrc
fi
