[manager]
prepend_keymap = [
  { on = [
    "l",
  ], run = "plugin --sync smart-enter", desc = "Enter the child directory, or open the file" },

  { on = [
    "T",
  ], run = "plugin --sync max-preview", desc = "Maximize or restore preview" },

  { on = [
    "<C-s>",
  ], run = 'shell "$SHELL" --block --confirm', desc = "Open shell here" },

  { on = [
    "p",
  ], run = "plugin --sync smart-paste", desc = "Paste into the hovered directory or CWD" },

  { on = [
    "y",
  ], run = [
    "yank",
    '''
	shell --confirm 'for path in "$@"; do echo "file://$path"; done | wl-copy -t text/uri-list'
''',
  ] },

  { on = "k", run = "plugin --sync arrow --args=-1" },

  { on = "j", run = "plugin --sync arrow --args=1" },
  { on = "K", run = "plugin --sync parent-arrow --args=-1" },
  { on = "J", run = "plugin --sync parent-arrow --args=1" },
  { on = "<A-j>", run = "seek 5" },
  { on = "<A-k>", run = "seek -5" },
]
append_keymap = [
  { on = [
    "g",
    "b",
  ], run = "cd ~/.config/bash", desc = "Go bash configuration directory", for = "unix" },
  { on = [
    "g",
    "z",
  ], run = "cd ~/.config/zsh", desc = "Go to zsh configuration directory", for = "unix" },
  { on = [
    "g",
    "l",
  ], run = "cd ~/.local/share", desc = "Go to the local share directory", for = "unix" },
  { on = [
    "g",
    "p",
  ], run = "cd ~/Projects", desc = "Go to the local share directory", for = "unix" },
  { on = [
    "g",
    "f",
  ], run = "cd ~/Files", desc = "Go to Files directory", for = "unix" },
  { on = [
    "g",
    "n",
  ], run = "cd ~/.config/nvim", desc = "Go to nvim configuration directory", for = "unix" },
  { on = [
    "g",
    "r",
  ], run = "cd ~/Repos", desc = "Go to repository directory", for = "unix" },
  { on = [
    "C",
  ], run = "plugin ouch --args=7z", desc = "Compress with ouch" },
]
