theme = "tokyonight"
[editor]
line-number = "relative"
mouse = false
bufferline = "always"

[editor.file-picker]
hidden = false
[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = [
  "diagnostics",
  "selections",
  "position",
  "file-encoding",
  "file-line-ending",
  "file-type",
]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"
[editor.cursor-shape]
insert = "bar"

[keys.insert]
"C-a" = "goto_line_start"
"C-e" = "goto_line_end"
"C-f" = "move_char_right"
"C-b" = "move_char_left"
"A-b" = "move_prev_word_start"
"A-f" = "move_next_word_start"

[keys.normal]
"A-q" = ":quit!"
"C-q" = ":wq"
"{" = ["goto_prev_paragraph", "collapse_selection"]
"}" = ["goto_next_paragraph", "collapse_selection"]
"0" = "goto_first_nonwhitespace"
"$" = "goto_line_end"
"^" = "goto_first_nonwhitespace"
"%" = "match_brackets"
"D" = [
  "extend_to_line_end",
  "yank_main_selection_to_clipboard",
  "delete_selection",
]
"G" = "goto_file_end"
V = ["select_mode", "extend_to_line_bounds"]
u = ["undo", "collapse_selection"]
esc = ["collapse_selection", "keep_primary_selection"]
S = "surround_add"

[keys.select]
"{" = ["extend_to_line_bounds", "goto_prev_paragraph"]
"}" = ["extend_to_line_bounds", "goto_next_paragraph"]
0 = "goto_first_nonwhitespace"
"$" = "goto_line_end"
"^" = "goto_first_nonwhitespace"
G = "goto_file_end"
D = ["extend_to_line_bounds", "delete_selection", "normal_mode"]
"%" = "match_brackets"
S = "surround_add"
u = ["switch_to_lowercase", "collapse_selection", "normal_mode"]
U = ["switch_to_uppercase", "collapse_selection", "normal_mode"]
i = "select_textobject_inner"
a = "select_textobject_around"
esc = ["collapse_selection", "keep_primary_selection", "normal_mode"]
