[misc]
no_retry = true
cleanup = false
notify_each_step = true
disable = ["emacs"]
no_self_update = false

[git]
max_concurrency = 8

# Additional git repositories to pull
repos = ["~/.config/zsh/antidote/", "~/Repos/*", "~/.config/yazi/plugins/*/"]

# Arguments to pass Git when pulling Repositories
arguments = "--rebase --autostash"


[windows]
accept_all_updates = false
wsl_update_pre_release = true

[npm]
# Use sudo if the NPM directory isn't owned by the current user
use_sudo = false

[firmware]
# Offer to update firmware; if false just check for and display available updates
upgrade = false

[flatpak]
# Use sudo for updating the system-wide installation
use_sudo = false
